# Generated by Django 3.0 on 2020-06-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=10)),
                ('deliveryID', models.IntegerField()),
                ('drone', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Drones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneID', models.IntegerField()),
                ('is_busy', models.BooleanField(default=False)),
                ('HostelNo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
