# Generated by Django 3.0 on 2020-06-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='HostelNo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
