# Generated by Django 3.0 on 2020-06-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_drones', '0002_auto_20200614_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='HostelNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drones',
            name='droneID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='drones',
            name='is_busy',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
