# Generated by Django 3.0 on 2020-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_drones', '0003_auto_20200614_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
