# Generated by Django 3.0.7 on 2020-06-24 12:50

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20200622_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_order',
            name='client_email',
            field=models.EmailField(default='trial@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='delivery_order',
            name='client_phone',
            field=phone_field.models.PhoneField(default=None, max_length=31),
        ),
    ]
