# Generated by Django 3.0.7 on 2020-06-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_auto_20200624_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_order',
            name='client_phone',
        ),
    ]
