# Generated by Django 3.0.7 on 2020-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_remove_delivery_order_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_order',
            name='client_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
