# Generated by Django 3.0.7 on 2020-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=10)),
                ('deliveryID', models.IntegerField()),
                ('drone', models.IntegerField()),
                ('orderstatus', models.BooleanField(default=False)),
                ('client_email', models.EmailField(default=None, max_length=254, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneID', models.IntegerField(unique=True)),
                ('deploy_pin', models.IntegerField(editable=False, unique=True)),
                ('busy', models.BooleanField(blank=True, default=False)),
                ('HostelNo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
