// Generated by gencpp from file offb/Data.msg
// DO NOT EDIT!


#ifndef OFFB_MESSAGE_DATA_H
#define OFFB_MESSAGE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offb
{
template <class ContainerAllocator>
struct Data_
{
  typedef Data_<ContainerAllocator> Type;

  Data_()
    : DroneID()
    , Hostel()  {
    }
  Data_(const ContainerAllocator& _alloc)
    : DroneID(_alloc)
    , Hostel(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _DroneID_type;
  _DroneID_type DroneID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Hostel_type;
  _Hostel_type Hostel;





  typedef boost::shared_ptr< ::offb::Data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offb::Data_<ContainerAllocator> const> ConstPtr;

}; // struct Data_

typedef ::offb::Data_<std::allocator<void> > Data;

typedef boost::shared_ptr< ::offb::Data > DataPtr;
typedef boost::shared_ptr< ::offb::Data const> DataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offb::Data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offb::Data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offb::Data_<ContainerAllocator1> & lhs, const ::offb::Data_<ContainerAllocator2> & rhs)
{
  return lhs.DroneID == rhs.DroneID &&
    lhs.Hostel == rhs.Hostel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offb::Data_<ContainerAllocator1> & lhs, const ::offb::Data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::offb::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offb::Data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::Data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::Data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::Data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::Data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offb::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d6232d0931f3e45599dc91639a5fb46";
  }

  static const char* value(const ::offb::Data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d6232d0931f3e45ULL;
  static const uint64_t static_value2 = 0x599dc91639a5fb46ULL;
};

template<class ContainerAllocator>
struct DataType< ::offb::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offb/Data";
  }

  static const char* value(const ::offb::Data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offb::Data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string DroneID\n"
"string Hostel\n"
;
  }

  static const char* value(const ::offb::Data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offb::Data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DroneID);
      stream.next(m.Hostel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offb::Data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offb::Data_<ContainerAllocator>& v)
  {
    s << indent << "DroneID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.DroneID);
    s << indent << "Hostel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Hostel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFB_MESSAGE_DATA_H
