// Generated by gencpp from file offb/Delivery.msg
// DO NOT EDIT!


#ifndef OFFB_MESSAGE_DELIVERY_H
#define OFFB_MESSAGE_DELIVERY_H

#include <ros/service_traits.h>


#include <offb/DeliveryRequest.h>
#include <offb/DeliveryResponse.h>


namespace offb
{

struct Delivery
{

typedef DeliveryRequest Request;
typedef DeliveryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Delivery
} // namespace offb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offb::Delivery > {
  static const char* value()
  {
    return "87b4be1048437cbe6f7e4ccfb825383b";
  }

  static const char* value(const ::offb::Delivery&) { return value(); }
};

template<>
struct DataType< ::offb::Delivery > {
  static const char* value()
  {
    return "offb/Delivery";
  }

  static const char* value(const ::offb::Delivery&) { return value(); }
};


// service_traits::MD5Sum< ::offb::DeliveryRequest> should match
// service_traits::MD5Sum< ::offb::Delivery >
template<>
struct MD5Sum< ::offb::DeliveryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offb::Delivery >::value();
  }
  static const char* value(const ::offb::DeliveryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offb::DeliveryRequest> should match
// service_traits::DataType< ::offb::Delivery >
template<>
struct DataType< ::offb::DeliveryRequest>
{
  static const char* value()
  {
    return DataType< ::offb::Delivery >::value();
  }
  static const char* value(const ::offb::DeliveryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offb::DeliveryResponse> should match
// service_traits::MD5Sum< ::offb::Delivery >
template<>
struct MD5Sum< ::offb::DeliveryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offb::Delivery >::value();
  }
  static const char* value(const ::offb::DeliveryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offb::DeliveryResponse> should match
// service_traits::DataType< ::offb::Delivery >
template<>
struct DataType< ::offb::DeliveryResponse>
{
  static const char* value()
  {
    return DataType< ::offb::Delivery >::value();
  }
  static const char* value(const ::offb::DeliveryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFB_MESSAGE_DELIVERY_H
