// Generated by gencpp from file offb/DeliveryResponse.msg
// DO NOT EDIT!


#ifndef OFFB_MESSAGE_DELIVERYRESPONSE_H
#define OFFB_MESSAGE_DELIVERYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offb
{
template <class ContainerAllocator>
struct DeliveryResponse_
{
  typedef DeliveryResponse_<ContainerAllocator> Type;

  DeliveryResponse_()
    : success(false)  {
    }
  DeliveryResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::offb::DeliveryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offb::DeliveryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeliveryResponse_

typedef ::offb::DeliveryResponse_<std::allocator<void> > DeliveryResponse;

typedef boost::shared_ptr< ::offb::DeliveryResponse > DeliveryResponsePtr;
typedef boost::shared_ptr< ::offb::DeliveryResponse const> DeliveryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offb::DeliveryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offb::DeliveryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offb::DeliveryResponse_<ContainerAllocator1> & lhs, const ::offb::DeliveryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offb::DeliveryResponse_<ContainerAllocator1> & lhs, const ::offb::DeliveryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::offb::DeliveryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offb::DeliveryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::DeliveryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::DeliveryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::DeliveryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::DeliveryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offb::DeliveryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::offb::DeliveryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::offb::DeliveryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offb/DeliveryResponse";
  }

  static const char* value(const ::offb::DeliveryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offb::DeliveryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::offb::DeliveryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offb::DeliveryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeliveryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offb::DeliveryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offb::DeliveryResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFB_MESSAGE_DELIVERYRESPONSE_H
