// Generated by gencpp from file offb/Web_Input.msg
// DO NOT EDIT!


#ifndef OFFB_MESSAGE_WEB_INPUT_H
#define OFFB_MESSAGE_WEB_INPUT_H

#include <ros/service_traits.h>


#include <offb/Web_InputRequest.h>
#include <offb/Web_InputResponse.h>


namespace offb
{

struct Web_Input
{

typedef Web_InputRequest Request;
typedef Web_InputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Web_Input
} // namespace offb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::offb::Web_Input > {
  static const char* value()
  {
    return "93721527c216f57d672506df413f1fd8";
  }

  static const char* value(const ::offb::Web_Input&) { return value(); }
};

template<>
struct DataType< ::offb::Web_Input > {
  static const char* value()
  {
    return "offb/Web_Input";
  }

  static const char* value(const ::offb::Web_Input&) { return value(); }
};


// service_traits::MD5Sum< ::offb::Web_InputRequest> should match
// service_traits::MD5Sum< ::offb::Web_Input >
template<>
struct MD5Sum< ::offb::Web_InputRequest>
{
  static const char* value()
  {
    return MD5Sum< ::offb::Web_Input >::value();
  }
  static const char* value(const ::offb::Web_InputRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::offb::Web_InputRequest> should match
// service_traits::DataType< ::offb::Web_Input >
template<>
struct DataType< ::offb::Web_InputRequest>
{
  static const char* value()
  {
    return DataType< ::offb::Web_Input >::value();
  }
  static const char* value(const ::offb::Web_InputRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::offb::Web_InputResponse> should match
// service_traits::MD5Sum< ::offb::Web_Input >
template<>
struct MD5Sum< ::offb::Web_InputResponse>
{
  static const char* value()
  {
    return MD5Sum< ::offb::Web_Input >::value();
  }
  static const char* value(const ::offb::Web_InputResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::offb::Web_InputResponse> should match
// service_traits::DataType< ::offb::Web_Input >
template<>
struct DataType< ::offb::Web_InputResponse>
{
  static const char* value()
  {
    return DataType< ::offb::Web_Input >::value();
  }
  static const char* value(const ::offb::Web_InputResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OFFB_MESSAGE_WEB_INPUT_H
