// Generated by gencpp from file offb/Web_InputRequest.msg
// DO NOT EDIT!


#ifndef OFFB_MESSAGE_WEB_INPUTREQUEST_H
#define OFFB_MESSAGE_WEB_INPUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offb
{
template <class ContainerAllocator>
struct Web_InputRequest_
{
  typedef Web_InputRequest_<ContainerAllocator> Type;

  Web_InputRequest_()
    : DroneID()
    , hostel_to()  {
    }
  Web_InputRequest_(const ContainerAllocator& _alloc)
    : DroneID(_alloc)
    , hostel_to(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _DroneID_type;
  _DroneID_type DroneID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hostel_to_type;
  _hostel_to_type hostel_to;





  typedef boost::shared_ptr< ::offb::Web_InputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offb::Web_InputRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Web_InputRequest_

typedef ::offb::Web_InputRequest_<std::allocator<void> > Web_InputRequest;

typedef boost::shared_ptr< ::offb::Web_InputRequest > Web_InputRequestPtr;
typedef boost::shared_ptr< ::offb::Web_InputRequest const> Web_InputRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offb::Web_InputRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offb::Web_InputRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offb::Web_InputRequest_<ContainerAllocator1> & lhs, const ::offb::Web_InputRequest_<ContainerAllocator2> & rhs)
{
  return lhs.DroneID == rhs.DroneID &&
    lhs.hostel_to == rhs.hostel_to;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offb::Web_InputRequest_<ContainerAllocator1> & lhs, const ::offb::Web_InputRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::offb::Web_InputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offb::Web_InputRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::Web_InputRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offb::Web_InputRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::Web_InputRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offb::Web_InputRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offb::Web_InputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa1416e6c2a4297d2865c0f4eea0c20d";
  }

  static const char* value(const ::offb::Web_InputRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa1416e6c2a4297dULL;
  static const uint64_t static_value2 = 0x2865c0f4eea0c20dULL;
};

template<class ContainerAllocator>
struct DataType< ::offb::Web_InputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offb/Web_InputRequest";
  }

  static const char* value(const ::offb::Web_InputRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offb::Web_InputRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string DroneID\n"
"string hostel_to\n"
;
  }

  static const char* value(const ::offb::Web_InputRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offb::Web_InputRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DroneID);
      stream.next(m.hostel_to);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Web_InputRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offb::Web_InputRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offb::Web_InputRequest_<ContainerAllocator>& v)
  {
    s << indent << "DroneID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.DroneID);
    s << indent << "hostel_to: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hostel_to);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFB_MESSAGE_WEB_INPUTREQUEST_H
