# Generated by Django 3.0.7 on 2020-06-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drones',
            new_name='Drone',
        ),
    ]
