# Generated by Django 3.0.7 on 2020-06-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20200622_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='deploy_pin',
            field=models.IntegerField(unique=True),
        ),
    ]
