# Generated by Django 3.0.7 on 2020-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_auto_20200619_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery_order',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
